name: CI/CD using actions & docker

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set prod.yml
        run: |
          cd ./src/main/resources
          sed -i 's|${DB_URL}|'"${{ secrets.DB_URL }}"'|g' application-prod.yml
          sed -i 's|${DB_USERNAME}|'"${{ secrets.DB_USERNAME }}"'|g' application-prod.yml
          sed -i 's|${DB_PASSWORD}|'"${{ secrets.DB_PASSWORD }}"'|g' application-prod.yml
          sed -i 's|${KAKAO_CLIENT_ID}|'"${{ secrets.KAKAO_CLIENT_ID }}"'|g' application-prod.yml
          sed -i 's|${KAKAO_CLIENT_SECRET}|'"${{ secrets.KAKAO_CLIENT_SECRET }}"'|g' application-prod.yml
          sed -i 's|${NAVER_CLIENT_ID}|'"${{ secrets.NAVER_CLIENT_ID }}"'|g' application-prod.yml
          sed -i 's|${NAVER_CLIENT_SECRET}|'"${{ secrets.NAVER_CLIENT_SECRET }}"'|g' application-prod.yml

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Docker build and push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            sudo usermod -aG docker $USER
            sudo docker stop reflogdocker || true
            sudo docker rm reflogdocker || true
            sudo docker image rm ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
            sudo docker run -e SPRING_PROFILES_ACTIVE=prod \
                            -e DB_URL=${{ secrets.DB_URL }} \
                            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
                            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                            -e EC2_HOST=${{ secrets.HOST_PROD }} \
                            -e KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
                            -e KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }} \
                            -e KAKAO_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} \
                            -e KAKAO_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }} \
                            --name reflogdocker -p 8080:8080 -d ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
            sudo docker image prune -f